== :doctype: asciidoc plain text

....
                    ΠΑΝΕΠΙΣΤΗΜΙΟ ΔΥΤΙΚΗΣ ΑΤΤΙΚΗΣ 
             ΤΜΗΜΑ ΜΗΧΑΝΙΚΩΝ ΠΛΗΡΟΦΟΡΙΚΗΣ ΚΑΙ ΥΠΟΛΟΓΙΣΤΩΝ    
                  ΥΠΟΛΟΓΙΣΤΙΚΗ ΝΕΦΟΥΣ ΚΑΙ ΥΠΗΡΕΣΙΕΣ 
                  ΤΕΛΙΚΗ ΕΡΓΑΣΙΑ ΕΞΑΜΗΝΟΥ 2022-2023
                        
....

================================================================================
ΦΟΙΤΗΤΕΣ ΟΜΑΔΑΣ: 1. ΠΑΡΑΣΚΕΥΟΠΟΥΛΟΣ ΧΡΗΣΤΟΣ - 141158 +
2. ΧΑΡΑΥΓΗΣ ΑΛΕΞΑΝΔΡΟΣ - 713242017067

....
                        3.14 - JAVA-CLOUD APP 
                        
....

[width="48%",cols="100%",options="header",]
|===
|Α. ΣΥΝΟΠΤΙΚΗ ΠΕΡΙΓΡΑΦΗ ΕΦΑΡΜΟΓΗΣ |
|Στην παρούσα εφαρμογή ” 3.14 JAVA CLOUD ” υλοποιείται ουσιαστικά , η
δημιουργία μίας διαδικτυακής εφαρμογής η οποία έχει FRONT-END , BACK-END
και DATABASE υλοποίηση .
|===

=== B. ΧΑΡΑΚΤΗΡΙΣΤΙΚΑ ΤΗΣ ΕΦΑΡΜΟΓΗΣ |

[arabic]
. ΧΑΡΑΚΤΗΡΙΣΤΙΚΑ ΥΠΗΡΕΣΙΑΣ FRONT-END Ο ΚΩΔΙΚΑΣ ΤΗΣ ΥΠΗΡΕΣΙΑΣ FRONT END
ΕΙΝΑΙ ΓΡΑΜΜΕΝΟΣ ΣΕ VUE .
. ΧΑΡΑΚΤΗΡΙΣΤΙΚΑ ΥΠΗΡΕΣΙΑΣ BACK-END : Ο ΚΩΔΙΚΑΣ ΤΗΣ ΥΠΗΡΕΣΙΑΣ ΒACK ΕΙΝΑΙ
ΓΡΑΜΜΕΝΟΣ ΣΕ JAVA SPRINGBOOT .
. ΧΑΡΑΚΤΗΡΙΣΤΙΚΑ ΥΠΗΡΕΣΙΑΣ DATABASE : ΧΡΗΣΗ MYSQL LOCALHOST

[cols="",]
|===
|Γ. ΛΕΙΤΟΥΡΓΙΑ ΤΗΣ ΕΦΑΡΜΟΓΗΣ |
|===

Η παρούσα εφαρμογή υλοποιεί μία σελίδα σύνδεσης σε έναν οργανισμό
χρησιμοποιόντας credentials όπως username και password . Παράλληλα
υλοποιείται η ενημέρωση της βάσης στο πίσω μέρος της εφαρμογής και
προφανώς υπάρχει το ανάλογο user interface κατά την σύνδεση του
χειριστή-χρήστη.

Ας σημειωθεί ότι κάθε παραπάνω χαρακτηριστικό διαθέτει dockerfile για
την χρήση του στο docker ως container.
