spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Takis1234
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
